/* eslint-disable @next/next/no-html-link-for-pages */
import { desc, eq } from "drizzle-orm";
import { getDb } from "../../../../../db";
import { auditLogs } from "../../../../../db/schema";
import { getActor } from "../../../../lib/server/authz";
import { getCeoPartnerDetail } from "../../../../lib/server/ceo-partner-management";
import { currentRequest } from "../../../../lib/server/current-request";
import { isInternalEccomiPartner } from "../../../../lib/server/partner-control-rules";
import CeoLoginFallback from "../../../ceo-login-fallback";
import "../../../ceo-server.css";
import "../../partners.css";
import "../../premium.css";

type Props={params:Promise<{id:string}>;searchParams?:Promise<Record<string,string|string[]|undefined>>};
const first=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]||"":v||"";
function shortDate(v:string|null){if(!v)return"—";const d=new Date(v);if(Number.isNaN(d.getTime()))return"—";return new Intl.DateTimeFormat("it-IT",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Rome"}).format(d)}

export default async function PartnerAccessPage({params,searchParams}:Props){
 const {id}=await params;const q=searchParams?await searchParams:{};const request=await currentRequest(`/ceo/partners/${id}/accessi`);const actor=await getActor(request);
 if(!actor)return <CeoLoginFallback/>;
 if(actor.role!=="CEO")return <main className="ceo-server-login"><section className="ceo-server-login__card"><h1>Area riservata al CEO</h1></section></main>;
 const detail=await getCeoPartnerDetail(request,id);
 if(!detail)return <main className="ceo-server-login"><section className="ceo-server-login__card"><h1>Partner non trovato</h1><a className="ceo-server-primary" href="/ceo/partners">Torna ai Partner</a></section></main>;
 const partner=detail.partner;const internal=isInternalEccomiPartner(partner.name,partner.legalName);
 const events=detail.preview?[]:await getDb().select({action:auditLogs.action,entityId:auditLogs.entityId,createdAt:auditLogs.createdAt}).from(auditLogs).where(eq(auditLogs.entityType,"partner_user")).orderBy(desc(auditLogs.createdAt)).limit(1000);
 const state=new Map<string,{status:string,lastLogin:string|null}>();
 for(const user of detail.users){const e=events.filter(x=>x.entityId.trim().toLowerCase()===user.email.trim().toLowerCase());const lastLogin=e.find(x=>x.action==="PARTNER_LOGIN")?.createdAt||null;const life=e.find(x=>["PARTNER_ACCESS_DISABLED","PARTNER_ADMIN_INVITED","PARTNER_ADMIN_INVITE_RESENT","PARTNER_ACCOUNT_ACTIVATED","PARTNER_ACCOUNT_REACTIVATED"].includes(x.action));const status=user.active?"ATTIVO":life?.action==="PARTNER_ACCESS_DISABLED"?"DISATTIVATO":life?.action?.includes("INVITE")?"INVITO INVIATO":"NON ATTIVO";state.set(user.email,{status,lastLogin})}
 const inviteSent=first(q.inviteSent)==="1",invitePreview=first(q.invitePreview)==="1",disabled=first(q.accessDisabled)==="1",disablePreview=first(q.accessPreview)==="1",deleted=first(q.accessDeleted)==="1",deletePreview=first(q.accessDeletePreview)==="1",accessError=first(q.accessError),eventEmail=first(q.inviteEmail)||first(q.accessEmail);
 const simulatedInactive=detail.preview&&Boolean(eventEmail)&&(invitePreview||disablePreview||deletePreview);const activeCount=internal?"INTERNO":Math.max(0,partner.activeUsers-(simulatedInactive?1:0));const visibleUsers=detail.preview&&deletePreview&&eventEmail?detail.users.filter(u=>u.email.trim().toLowerCase()!==eventEmail.trim().toLowerCase()):detail.users;
 const completed=inviteSent||invitePreview||disabled||disablePreview||deleted||deletePreview;
 const message=deletePreview?"Simulazione preview: accesso eliminato":deleted?"Accesso eliminato dalla società Partner":invitePreview?"Simulazione preview: invito pronto":disablePreview?"Simulazione preview: accesso disattivato":disabled?"Accesso disattivato":"Invito inviato con Resend";
 return <main className="ceo-server-page partner-premium-page">
  <header className="ceo-server-bar"><div className="ceo-server-bar__brand"><span>🚙</span><div><strong>ECCOMI</strong><small>NOLEGGIO</small></div></div><a href={`/ceo/partners/${encodeURIComponent(id)}#accessi`}>← Scheda Partner</a></header>
  <section className="partner-premium-hero"><div className="partner-premium-identity"><div className="partner-premium-monogram">🔐</div><div><small>CEO · GESTIONE ACCESSI</small><h1>Accessi · {partner.name}</h1><p>{partner.legalName}</p></div></div><div className="partner-premium-state"><span className="partner-premium-eyebrow">ACCOUNT ATTIVI</span><span className="partner-pill partner-pill--active">{activeCount}</span></div></section>
  {completed?<section className="partner-attention-panel partner-attention-panel--regular"><div className="partner-attention-panel__icon">✓</div><div className="partner-attention-panel__copy"><small>OPERAZIONE COMPLETATA</small><strong>{message}</strong><span>{eventEmail||"Account Partner aggiornato"}</span></div></section>:null}
  {accessError?<section className="partner-attention-panel partner-attention-panel--intervention"><div className="partner-attention-panel__icon">!</div><div className="partner-attention-panel__copy"><small>OPERAZIONE NON COMPLETATA</small><strong>{accessError}</strong></div></section>:null}
  {internal?<section className="partner-detail-section"><div className="partner-detail-section__head"><div><h2>Struttura interna ECCOMI</h2><p>Nessun account Area Partner necessario.</p></div></div></section>:<div className="partner-detail-stack">
   <section className="partner-detail-section"><div className="partner-detail-section__head"><div><h2>Invita Partner Admin</h2><p>Il destinatario riceve il link ECCOMI e sceglie la propria password.</p></div><span className="partner-premium-section-number">01</span></div><form method="post" action={`/api/ceo/partners/${encodeURIComponent(id)}/invite`} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:12,alignItems:"end"}}><label style={{display:"grid",gap:6,fontWeight:800}}>Nome e cognome<input name="displayName" required minLength={2} defaultValue={partner.contactName||""}/></label><label style={{display:"grid",gap:6,fontWeight:800}}>Email<input name="email" type="email" required defaultValue={partner.contactEmail||""}/></label><button className="ceo-server-primary" type="submit">Invia invito Partner Admin</button></form></section>
   <section className="partner-detail-section"><div className="partner-detail-section__head"><div><h2>Account della società</h2><p><strong>Disattiva</strong> sospende l’accesso. <strong>Elimina accesso</strong> rimuove il collegamento alla società e non blocca più la cancellazione del Partner.</p></div><span className="partner-premium-section-number">02</span></div><div className="partner-table-wrap"><table className="partner-table"><thead><tr><th>Nome</th><th>Email</th><th>Stato</th><th>Ultimo accesso</th><th></th></tr></thead><tbody>{visibleUsers.length?visibleUsers.map(user=>{const s=state.get(user.email)||{status:user.active?"ATTIVO":"NON ATTIVO",lastLogin:null};const match=detail.preview&&Boolean(eventEmail)&&user.email.trim().toLowerCase()===eventEmail.trim().toLowerCase();const pInv=match&&invitePreview,pDis=match&&disablePreview;const displayStatus=pInv?"INVITO INVIATO":pDis?"DISATTIVATO":s.status;const canDisable=user.active&&!pInv&&!pDis;const canDelete=(!user.active||pDis)&&!pInv;return <tr key={user.email}><td>{user.displayName}</td><td>{user.email}</td><td>{displayStatus}</td><td>{shortDate(s.lastLogin)}</td><td>{canDisable?<form method="post" action={`/api/ceo/partners/${encodeURIComponent(id)}/access`}><input type="hidden" name="email" value={user.email}/><input type="hidden" name="action" value="DISABLE"/><button type="submit">Disattiva</button></form>:canDelete?<form method="post" action={`/api/ceo/partners/${encodeURIComponent(id)}/access`}><input type="hidden" name="email" value={user.email}/><input type="hidden" name="action" value="DELETE"/><button type="submit" style={{color:"#9f1d1d",fontWeight:900}}>Elimina accesso</button></form>:<span>Reinvia dal modulo sopra</span>}</td></tr>}):<tr><td className="partner-empty-row" colSpan={5}>Nessun account configurato. Il Partner non ha più accessi collegati.</td></tr>}</tbody></table></div></section>
   <section className="partner-detail-section"><div className="partner-detail-section__head"><div><h2>Flusso di sicurezza</h2><p>Il ruolo Partner viene verificato nel database applicativo a ogni richiesta.</p></div><span className="partner-premium-section-number">03</span></div><div className="partner-attention-panel partner-attention-panel--regular" style={{margin:0}}><div className="partner-attention-panel__icon">✓</div><div className="partner-attention-panel__copy"><small>ISOLAMENTO</small><strong>Accesso governato da ECCOMI</strong><span>Eliminando il collegamento applicativo, l’account non può più entrare nell’Area Partner.</span></div></div></section>
  </div>}
 </main>;
}
