import { sql } from "drizzle-orm";
import { boolean, index, integer, pgTable, text, uniqueIndex } from "drizzle-orm/pg-core";

export const partners = pgTable("partners", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  legalName: text("legal_name").notNull(),
  status: text("status").notNull().default("ACTIVE"),
  contactName: text("contact_name"),
  contactEmail: text("contact_email"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const users = pgTable("users", {
  email: text("email").primaryKey(),
  displayName: text("display_name").notNull(),
  role: text("role").notNull(),
  partnerId: text("partner_id").references(() => partners.id),
  active: boolean("active").notNull().default(true),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("users_partner_idx").on(table.partnerId)]);

export const promotions = pgTable("promotions", {
  id: text("id").primaryKey(),
  offerNumber: text("offer_number").notNull(),
  provider: text("provider").notNull(),
  partnerId: text("partner_id").notNull().references(() => partners.id),
  sourceLabel: text("source_label").notNull(),
  brand: text("brand").notNull(),
  model: text("model").notNull(),
  version: text("version").notNull().default(""),
  monthlyGrossCents: integer("monthly_gross_cents").notNull(),
  monthlyNetCents: integer("monthly_net_cents"),
  depositGrossCents: integer("deposit_gross_cents").notNull().default(0),
  durationMonths: integer("duration_months").notNull(),
  totalKm: integer("total_km").notNull(),
  validFrom: text("valid_from"),
  validUntil: text("valid_until").notNull(),
  delivery: text("delivery").notNull().default(""),
  fuel: text("fuel").notNull().default(""),
  transmission: text("transmission").notNull().default(""),
  color: text("color").notNull().default(""),
  powerKw: text("power_kw").notNull().default(""),
  servicesJson: text("services_json").notNull().default("[]"),
  warningsJson: text("warnings_json").notNull().default("[]"),
  confidence: text("confidence").notNull().default("media"),
  status: text("status").notNull().default("PENDING_APPROVAL"),
  quoteKey: text("quote_key"),
  quoteFileName: text("quote_file_name"),
  coverKey: text("cover_key"),
  coverSourceKind: text("cover_source_kind"),
  coverSourceUrl: text("cover_source_url"),
  coverAttribution: text("cover_attribution"),
  automationStatus: text("automation_status").notNull().default("READY"),
  automationError: text("automation_error"),
  extractionMethod: text("extraction_method").notNull().default("RULES"),
  shopifyProductId: text("shopify_product_id"),
  shopifyHandle: text("shopify_handle"),
  shopifyUrl: text("shopify_url"),
  shopifyCollectionId: text("shopify_collection_id"),
  approvedBy: text("approved_by"),
  approvedAt: text("approved_at"),
  publishedAt: text("published_at"),
  createdBy: text("created_by").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("promotions_offer_provider_idx").on(table.offerNumber, table.provider),
  index("promotions_partner_idx").on(table.partnerId),
  index("promotions_status_idx").on(table.status),
  index("promotions_valid_until_idx").on(table.validUntil),
]);

export const leads = pgTable("leads", {
  id: text("id").primaryKey(),
  promotionId: text("promotion_id").notNull().references(() => promotions.id),
  partnerId: text("partner_id").notNull().references(() => partners.id),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  phone: text("phone").notNull(),
  email: text("email").notNull(),
  province: text("province"),
  customerType: text("customer_type"),
  businessName: text("business_name"),
  vatNumber: text("vat_number"),
  tradeIn: boolean("trade_in").notNull().default(false),
  contactWindow: text("contact_window"),
  status: text("status").notNull().default("NEW"),
  documentStatus: text("document_status").notNull().default("PENDING_EMAIL_VERIFICATION"),
  emailVerificationStatus: text("email_verification_status").notNull().default("PENDING"),
  privacyVersion: text("privacy_version").notNull(),
  privacyAcceptedAt: text("privacy_accepted_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  marketingConsent: boolean("marketing_consent").notNull().default(false),
  submissionKey: text("submission_key"),
  source: text("source").notNull().default("SHOPIFY"),
  assignedAt: text("assigned_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("leads_submission_key_idx").on(table.submissionKey),
  index("leads_partner_idx").on(table.partnerId),
  index("leads_promotion_idx").on(table.promotionId),
  index("leads_status_idx").on(table.status),
]);

export const commissions = pgTable("commissions", {
  id: text("id").primaryKey(),
  leadId: text("lead_id").notNull().references(() => leads.id),
  partnerId: text("partner_id").notNull().references(() => partners.id),
  amountCents: integer("amount_cents").notNull(),
  status: text("status").notNull().default("ACCRUED"),
  accruedAt: text("accrued_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  invoicedAt: text("invoiced_at"),
  paidAt: text("paid_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [index("commissions_partner_idx").on(table.partnerId)]);

export const auditLogs = pgTable("audit_logs", {
  id: text("id").primaryKey(),
  actorEmail: text("actor_email").notNull(),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  payloadJson: text("payload_json").notNull().default("{}"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  index("audit_entity_idx").on(table.entityType, table.entityId),
  index("audit_actor_idx").on(table.actorEmail),
]);

export const hubEvents = pgTable("hub_events", {
  id: text("id").primaryKey(),
  eventType: text("event_type").notNull(),
  ecosystem: text("ecosystem").notNull().default("ECCOMI_NOLEGGIO"),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  title: text("title").notNull(),
  payloadJson: text("payload_json").notNull().default("{}"),
  actorEmail: text("actor_email").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  index("hub_events_entity_idx").on(table.entityType, table.entityId),
  index("hub_events_created_idx").on(table.createdAt),
]);

export const integrations = pgTable("integrations", {
  id: text("id").primaryKey(),
  provider: text("provider").notNull(),
  shopDomain: text("shop_domain").notNull(),
  shopName: text("shop_name").notNull().default(""),
  storefrontUrl: text("storefront_url").notNull().default(""),
  clientId: text("client_id").notNull(),
  encryptedClientSecret: text("encrypted_client_secret").notNull(),
  publicationId: text("publication_id").notNull(),
  publicationLabel: text("publication_label").notNull().default("Negozio online"),
  publicationAutoPublish: boolean("publication_auto_publish").notNull().default(false),
  status: text("status").notNull().default("CONNECTED"),
  connectedBy: text("connected_by").notNull(),
  connectedAt: text("connected_at").notNull(),
  verifiedAt: text("verified_at").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("integrations_provider_idx").on(table.provider),
]);

export const aiIntegrations = pgTable("ai_integrations", {
  id: text("id").primaryKey(),
  provider: text("provider").notNull().default("OPENAI"),
  encryptedApiKey: text("encrypted_api_key").notNull(),
  textModel: text("text_model").notNull().default("gpt-5.6-terra"),
  imageModel: text("image_model").notNull().default("gpt-image-2"),
  status: text("status").notNull().default("CONNECTED"),
  connectedBy: text("connected_by").notNull(),
  connectedAt: text("connected_at").notNull(),
  verifiedAt: text("verified_at").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex("ai_integrations_provider_idx").on(table.provider),
]);
